Create Database order_directory;
use order_directory;
CREATE TABLE supplier(SUPP_ID int primary key,SUPP_NAME varchar(50) NOT NULL,SUPP_CITY varchar(50),SUPP_PHONE varchar(10) NOT NULL
);
CREATE TABLE customer(CUS_ID INT NOT NULL,CUS_NAME VARCHAR(20) NOT NULL,CUS_PHONE VARCHAR(10) NOT NULL,CUS_CITY varchar(30) NOT NULL,CUS_GENDER CHAR,PRIMARY KEY (CUS_ID));
CREATE TABLE category (CAT_ID INT NOT NULL,CAT_NAME VARCHAR(20) NOT NULL,PRIMARY KEY (CAT_ID));

CREATE TABLE product (PRO_ID INT NOT NULL,PRO_NAME VARCHAR(20) NOT NULL DEFAULT "Dummy",PRO_DESC VARCHAR(60),CAT_ID INT NOT NULL,PRIMARY KEY (PRO_ID),FOREIGN KEY (CAT_ID) REFERENCES CATEGORY (CAT_ID));
CREATE TABLE supplier_pricing (PRICING_ID INT NOT NULL,PRO_ID INT NOT NULL,SUPP_ID INT NOT NULL,SUPP_PRICE INT DEFAULT 0,PRIMARY KEY (PRICING_ID),FOREIGN KEY (PRO_ID) REFERENCES PRODUCT (PRO_ID),
FOREIGN KEY (SUPP_ID) REFERENCES SUPPLIER(SUPP_ID));
CREATE TABLE orders (ORD_ID INT NOT NULL,ORD_AMOUNT INT NOT NULL,ORD_DATE DATE,CUS_ID INT NOT NULL,PRICING_ID INT NOT NULL,PRIMARY KEY (ORD_ID),FOREIGN KEY (CUS_ID) REFERENCES CUSTOMER(CUS_ID),FOREIGN KEY (PRICING_ID) REFERENCES SUPPLIER_PRICING(PRICING_ID));
CREATE TABLE rating (RAT_ID INT NOT NULL,ORD_ID INT NOT NULL,RAT_RATSTARSINT INT NOT NULL ,PRIMARY KEY (RAT_ID),FOREIGN KEY (ORD_ID) REFERENCES orders(ORD_ID));